package com.gunungsewu.database.service;

public interface Constant {
	final String GET_USER_BY_PHONE_NO = "GET_USER_BY_PHONE_NO";
	final String GET_USER_BY_CHAT_ID = "GET_USER_BY_CHAT_ID";
	final String SAVE_CHAT_ID = "SAVE_CHAT_ID";
	final String GET_PO = "GET_PO";
	final String GET_PO_WOVEN = "GET_PO_WOVEN";
	final String GET_PO_PRINTED = "GET_PO_PRINTED";
	final String GET_REORDER_PO = "GET_REORDER_PO";
	final String GET_REORDER_PO_WOVEN = "GET_REORDER_PO_WOVEN";
	final String GET_REORDER_PO_PRINTED = "GET_REORDER_PO_PRINTED";
	final String GET_TOP_5_PO = "GET_TOP_5_PO";
	
	final String TEL_ORDER_TO_NLIS = "TEL_ORDER_TO_NLIS";
	final String TEL_ORDER_FROM_NLIS = "TEL_ORDER_FROM_NLIS";
	final String TEL_ISSUE_TO_JTRAC = "TEL_ISSUE_TO_JTRAC";
	final String TEL_ISSUE_FROM_JTRAC = "TEL_ISSUE_FROM_JTRAC";
	final String LINE_ORDER_TO_NLIS = "LINE_ORDER_TO_NLIS";
	final String LINE_ORDER_FROM_NLIS = "LINE_ORDER_FROM_NLIS";
	final String LINE_ISSUE_TO_JTRAC = "LINE_ISSUE_TO_JTRAC";
	final String LINE_ISSUE_FROM_JTRAC = "LINE_ISSUE_FROM_JTRAC";
	final String WEB_ORDER_TO_NLIS = "WEB_ORDER_TO_NLIS";
	final String WEB_ORDER_FROM_NLIS = "WEB_ORDER_FROM_NLIS";
	final String WEB_ISSUE_TO_JTRAC = "WEB_ISSUE_TO_JTRAC";
	final String WEB_ISSUE_FROM_JTRAC = "WEB_ISSUE_FROM_JTRAC";
	final String SHIPPING_NOTIFICATION_QUEUE = "SHIPPING_NOTIFICATION";
	
	
	final String CHECK_ORDER_CHAT = "CHECK_ORDER_CHAT";
	final String REORDER_CHAT = "REORDER_CHAT";
	final String KELUHAN_CHAT = "KELUHAN_CHAT";

}
